# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 264ebb649804b1153bf8c0964cb873aec77891361c9cb0a3dafc149d7d451e4709255fed21e78f43b45652793e7e802210fd3ff5d3e5190e368914780737de12

test:
  secret_key_base: 9df3feb385a27eb19f92f01b3923f13950f747994f03005a306862d5cdbb5fca452ed7e5dcce9b842a8c3038fb3cb4dd8dddcbaf718266a21f2ce3d6c14f05e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
